### ISSUE TITLE
Windows 10 1903

### ISSUE THREAD

**Issue by Poochsr** [mobilinkd/tnc3-firmware#9]
Trying to install new firmware. Windows 10 get error in Device manager under Universal serial bus controllers > Unknown USB Device (Device Descriptor Request Failure). This happens on both my laptops when trying to update firmware.

**Comment by mobilinkd** [comment]
Support issues are best addressed at support@mobilinkd.com or at https://groups.io/g/mobilinkd rather than here.

Are you following the instructions here? https://github.com/mobilinkd/tnc3-firmware/blob/master/WindowsFirmwareUpdate.md

I am going to close this as the the DFU bootloader used to update the firmware is hard-coded into the microcontroller and not something that can be changed by updating the TNC3 firmware.

**Comment by Poochsr** [comment]
Yes - following the instructions. I will create a support case.

 

Thanks,

Chuck Poch
